# The image of hpcacmbuild.azurecr.io/public/hpcpack/hpcacm:latest is built using src/Dcoker/Dockerfile,
# it should be repalced by your own build image.

FROM hpcacmbuild.azurecr.io/public/hpcpack/hpcacm:latest as final
WORKDIR /app/Dashboard
ENTRYPOINT ["dotnet", "Dashboard.dll"]
