FROM ubuntu AS angular
RUN apt-get update && apt-get install -y gnupg2
RUN apt-get install -y apt-utils
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
RUN npm install --unsafe-perm -g @angular/cli