FROM evancui/angularbuild:git AS final
WORKDIR /src
ADD https://api.github.com/repos/BabysbreathJJ/hpc-rest-bvt/compare/master...HEAD /dev/null
RUN git clone https://github.com/BabysbreathJJ/hpc-rest-bvt.git
WORKDIR /src/hpc-rest-bvt
RUN npm install
ENTRYPOINT ["npm", "start"]
