version: '3'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile

  jobdispatcher:
    image: jobdispatcher
    build:
      context: .
      dockerfile: services/JobDispatcher/Dockerfile


  bootstrap:
    image: bootstrap
    build:
      context: .
      dockerfile: Bootstrap/Dockerfile

